/*
 *   Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 *   Licensed under the Apache License, Version 2.0 (the "License").
 *   You may not use this file except in compliance with the License.
 *   A copy of the License is located at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   or in the "license" file accompanying this file. This file is distributed
 *   on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 *   express or implied. See the License for the specific language governing
 *   permissions and limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex */

#ifndef _Included_com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex
#define _Included_com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex
 * Method:    saveIndex
 * Signature: ([I[[FLjava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex_saveIndex
  (JNIEnv *, jclass, jintArray, jobjectArray, jstring, jobjectArray);

/*
 * Class:     com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex
 * Method:    queryIndex
 * Signature: ([FI[Ljava/lang/String;)[Lcom/amazon/opendistroforelasticsearch/knn/index/KNNQueryResult;
 */
JNIEXPORT jobjectArray JNICALL Java_com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex_queryIndex
  (JNIEnv *, jlong, jfloatArray, jint, jobjectArray);

/*
 * Class:     com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jlong JNICALL Java_com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex_init
  (JNIEnv *, jstring);

/*
 * Class:     com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex
 * Method:    gc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_amazon_opendistroforelasticsearch_knn_index_v1736_KNNIndex_gc
  (JNIEnv *, jlong);

#ifdef __cplusplus
}
#endif
#endif
