/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_elasticsearch_index_knn_v1736_KNNIndex */

#ifndef _Included_org_elasticsearch_index_knn_v1736_KNNIndex
#define _Included_org_elasticsearch_index_knn_v1736_KNNIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_elasticsearch_index_knn_v1736_KNNIndex
 * Method:    saveIndex
 * Signature: ([I[[FLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_elasticsearch_index_knn_v1736_KNNIndex_saveIndex
  (JNIEnv *, jclass, jintArray, jobjectArray, jstring);

/*
 * Class:     org_elasticsearch_index_knn_v1736_KNNIndex
 * Method:    queryIndex
 * Signature: ([FI)[Lorg/elasticsearch/index/knn/KNNQueryResult;
 */
JNIEXPORT jobjectArray JNICALL Java_org_elasticsearch_index_knn_v1736_KNNIndex_queryIndex
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     org_elasticsearch_index_knn_v1736_KNNIndex
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_elasticsearch_index_knn_v1736_KNNIndex_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_elasticsearch_index_knn_v1736_KNNIndex
 * Method:    gc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_elasticsearch_index_knn_v1736_KNNIndex_gc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
