/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex */

#ifndef _Included_com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex
#define _Included_com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex
 * Method:    save
 * Signature: ([I[[FLjava/lang/String;[Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex_save
  (JNIEnv *, jclass, jintArray, jobjectArray, jstring, jobjectArray, jstring, jstring);

/*
 * Class:     com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex
 * Method:    query
 * Signature: (J[FI)[Lcom/amazon/opendistroforelasticsearch/knn/index/KNNQueryResult;
 */
JNIEXPORT jobjectArray JNICALL Java_com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex_query
  (JNIEnv *, jclass, jlong, jfloatArray, jint);

/*
 * Class:     com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex
 * Method:    init
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex_init
  (JNIEnv *, jclass, jstring, jobjectArray, jstring);

/*
 * Class:     com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex
 * Method:    gc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex_gc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex
 * Method:    initLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_amazon_opendistroforelasticsearch_knn_index_nmslib_v2011_KNNNmsLibIndex_initLibrary
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
