name: Build and Test k-NN
on:
  push:
    branches:
      - master
      - opendistro-*

jobs:
  Build-k-NN:
    strategy:
      matrix:
        java: [14]

    name: Build and Test k-NN Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout k-NN
        uses: actions/checkout@v1

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Run build
        run: |
          ./gradlew build
